var GAME_LEVELS = [
  ["                                                                                                                                       ",
   "                                                                                                                                       ",
   "                                                                                                                                       ",
   "                                                                                                                                       ",
   "                                                                                                                                       ",
   "                                                                                                                                       ",
   "                                                                                                                                       ",
   "                                                                                                                                       ",
   "                                                                           f                  f                                        ",
   "                                                                           xx      xxxx       xx                                       ",
   "                                                                   xxxx                            xxxxx                               ",
   "                                                                   xxxx                                     xxx                        ",
   "                                                                   xxxxx                                                               ",
   "                   f  xxx          f            xxxxx        f     xxxxx                     xxxx                xx                    ",
   "            f  x   x  xxx      xx    xxxx    xxxxxxxxxxx    xxx    xxxxxx              f                                         f     ",
   "         x  x  x      xxx  S                    x  x  x      xxx    xxxxxxx            xxx          S                            xxxxx   ",
   "    @    x     x      xxx                     x  x  x      xxx    xxxxxxx                                f                           ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx        xxxxxxxxxxxyyyyyxxxxxxxxxxxxxxxxxxxxx          xxxxxxxxxxxxxxxxxxxxxxxxxxx         xxxx           ",
   "                            x!!!!!!!!x                                   x          x                         x!!!!!!!!!x              ",
   "                            x!!!!!!!!x                                   x          x                         xxxxxxxxxxx              ",
   "                            xxxxxxxxxx                                   x!!!!!!!!!!x                                                  ",
   "                                                                         x!!!!!!!!!!x                                                  ",
   "                                                                         xxxxxxxxxxxx                                                  ",
   "                                                                                                                                       "],
   
   
   
   
  ["                                                                                                                                                                                                                                 ",
   "                                                                                                                                                                                                                                 ",
   "                                                                                                                                                                                                                                 ",
   "                                                                                                                                                                                                                                 ",
   "                                                                                                                                                                                                                                 ",
   "                                                                            xxxxxxx                                                                                                                                              ",
   "                                                                         xxxxxxxxxxxxx                                                                                                                                           ",
   "                                                                       xxxxxx      xxxxx                                                                                                                                         ",
   "                                                                       xxxx          xxxx                                                                                                                                        ",
   "                                                                        xxxx  xx      xxx                                                                                                                                        ",
   "                                                             f            xxxx        xxx                                                                                                                                        ",
   "                                                          xxxxxx                      xxx                                                                                                                                        ",
   "                            f                                                        xxxx                                     x                                                                                                  ",
   "                        xxxxxxxxx                                                  xxxxxx          f                f         xxxx                                                                                               ",
   "                    xxxxxxxxxxxxxxxx                                 xxxxx         xxxxxx     xxxx  xxxxxx       xx     xx       xxxx                                                                                            ",
   "                  xxxxxxxxxxxxxxxxxxxx                                            xxxxxx                                                                                                                                         ",
   "               xxxxxxx           xxxxxxx                                      xxxxxx                                             y   xxx                                                                                         ",
   "            xxxxxxxx        xx    xxxxxxx              xxxxx              xxxxxx                                              yyyy      xxxx                                                                                     ",
   "          xxxxxxx           xxxx   xxxxxx          xxxxxxxxxx      xxxxxxxxx                               yy     yy      yyyy             xxx                      f                                                            ",
   "        xxxxxxxx             xxxxxxxxxxxx         xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                               xxx                 xxxxxxxxx                                                       ",
   "   @   xxxxxxxxxx f            xxxxxxxx           x                                                                                          xxx              xxxx       xxxxx                        xxxx                       ",
   "xxxxxxxxxxxxxxxxxxxx                            xxx                                                                                          xxx             xxx            xxxx                    xxx   xxx                 x  ",
   "                   x                            x                            xxxxxxxx                xxxxxxxxx       xxxxxxxx                 xxx           xx                 xxx                          xxx           f  xx  ",
   "                   x                            x                          xxxx  xxxxxx              xxxx   xxx    xxx   xxxx                  xxxx                              xx                xx         xxxx!!!!!!!xxxxx   ",
   "                   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                         xxx        xxxx           xxxx     xxx  xx      xxxx                   xxx!!!!!!!xxx                                   xxxxx           xxxxxxxxxxx     ",
   "                                                 x            xxxxxxxxxx              xxxxx           xxxx              xxxx               x       xxxxxxxxx                      xxxx!!!!!!!!!xxxx                xxxxxxx       ",
   "                                                 x                              f       xxxxxx         xxxx            xxxx                x         xxxxx                          xxxx!!!!!xxxx                                ",
   "                                                 x    S                                 xxxxxxx      xxxx               xxxx               x                                           xxxxxxx                                   ",
   "                                                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxx                     xxx    xxxxxxxxxx                                                                                     ",
   "                                                                                                                                                                                                                                 "],
  
  
  
  ["                                                                                                                                                                                                                                 ",
   "                                                                                                                                                                                                                                 ",
   "                                                                                                                                                                                                                                 ",
   "                                                                                                                                                                                                                                 ",
   "                                                                                                                                                                                                                                 ",
   "                                                                                                                                                                                                                                 ",
   "                                                                                                                                                                                                                                 ",
   "                                                                                                                                                                                                                                 ",
   "                                                                                                                                                                                                                                 ",
   "                                                                                                                                                                                                                                 ",
   "                                                                                                                                                                                                                                 ",
   "                                                                                                                                                                                                                                 ",
   "                                                                                                                                                                                                                                 ",
   "                                                                                                                                                                                                                                 ",
   "                                                                                                                                                                                                                                 ",
   "                                                                                                                                                                                                                                 ",
   "                                                                                                                                                                                                                                 ",
   "                                                                                                                                                                                                                                 ",
   "                                                                                                                                                                                                                                 ",
   "                                                                                                                                                                                                                                 ",
   "                                                                                                                                                                                                                                 ",
   "                                                                                                                                                                                                                                 ",
   "                                                                                                                                                                                                                                 ",
   "                                                                                                                                                                                                                                 ",
   "                                                                                                                                                                                                                                 ",
   "                                                                                                                                                                                                                                 ",
   "                                                                                                                                                                                                                                 ",
   "                                                                                                                                                                                                                                 ",
   "                                                                                                                                                                                                                                 ",
   "                                                    f            xxx                                                                                                                                                             ",
   "                                                  xxxxx         xx xx                               xxx                                                                                                                          ",
   "                                                 xx   xx         xxx                               xx xx                                                                                                                         ",
   "                                               xxxx   xxxx                                          xxx                       xxx                                                                                                ",
   "                                                xxx   xxx                       xxxxxxxxxxx                      f           xx xx             S                                                                                  ",
   "                                   f              xxxxx                       xxxxx     xxxxx                                 xxx                                                                                                ",
   "                                 xxxxx                                       xxxx          xxxx                xxxx                                                                                                              ",
   "                            xxxxxxxxxxxxxxxx                                xxx              xxx              xx  xx                                                                                                             ",
   "                          xx   xxxxxxxxxx   xx           xx        xx       xxx              xxx               xxxx                                   f                f               f                    f                    ",
   "                         xx   xxxxxxxxxxxx   xx          xx       xxxx      xxx              xxx                                   xxxx             xxxx             xxxx            xxxx                 xxxxx                  ",
   "                        xx   xxxxxxxxxxxxxx   xx                   xx       xxx              xxx                                  xx  xx           xx  xx           xx  xx          xx  xx       x       xxx xxx                 ",
   "       @       xx      xx   xxxxxxxxxxxxxxxx   xx                           xxx              xxx        xxxxx                      xxxx             xxxx             xxxx            xxxx                xxx xxx                 ",
   "      xxx     xxxx     xx   xxxxxxxxxxxxxxxx   xx        xxxx               xxx              xxx       xx   xx                                                                                            xxxxx                  ",
   "    xx   xx    xx      xxx   xxxxxxxxxxxxxx   xxx       xx  xx              xxxx            xxxx     xxxx   xxxx                                                                                                                 ",
   "    xx   xx            xxx   xxxxxxxxxxxxxx   xxx        xxxx                 xxxxx      xxxxx        xxx   xxx                              xxxx              xxx               xxx                                             ",
   "      xxx               xxxx    xxxxxxx     xxxx                                 xxxxxxxxxx             xxxxx                                                                                                                    ",
   "     S                                                              f                                                   xxxxxxxxxxxx!!!!!!!!!!!!!xxxxxxxxx!!!!!!!!!!xxxxxxx!!!!!!!!!xxxxxxxx!!!!!!!!!!!                          ",
   "                                                   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                                                                             "],

   
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
